name: "Backend"

services:
  database:
    hostname: ${POSTGRES_HOST}
    container_name: database
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    command:
      - -p
      - "5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:7.4-alpine
    restart: unless-stopped
    command: >
      sh -c "redis-server --appendonly yes
      --save 60 1
      --requirepass ${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:6379"
#    volumes:
#      - redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend

#  api:
#    container_name: api
#    build: .
#    restart: unless-stopped
#    env_file:
#      - .env
#    ports:
#      - "${PORT}:${PORT}"
#    depends_on:
#      database:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#    networks:
#      - backend

networks:
  backend:
    driver: bridge
#
#volumes:
#  postgres_data:
#  redis_data:
